<?php

define('ACCESS_ADMIN', 'ADMINISTRATION_CO');

// GESTION Admin <-> Artisan 
define('ACCESS_DECLARE_ARTISAN', 'DCLMEETADARTISAN');
define('ACCESS_APPROVE_ARTISAN', 'APRVMEETADARTISAN');
define('ACCESS_REJECT_ARTISAN', 'REJMEETADARTISAN');
define('ACCESS_REMOVE_ARTISAN', 'DELMEETADARTISAN');

// GESTION Particulier <-> Artisan
define('ACCESS_APPROVE_PARTICULIER', 'APRVMEETADPARTICULIER');
define('ACCESS_REJECT_PARTICULIER', 'REJMEETADPARTICULIER');